### PR TITLE
Changes to frontend

### PR DESCRIPTION
**Pull request by webflo**
Follow up to https://github.com/drupal-composer/drupal-packagist/issues/1

@winmillwill wrote:

> I think we should just have a few http server rewrites for the front page and other potentially confusing paths so that it's clear that we don't support the normal packagist.org workflow (register, login, add a repo). This way we can leave it on and use the experimental auto update functionality.
## Todos
- [x] Remove links "Create a new account", "Login", "Submit Package"
- [x] Adjust links in footer
- [x] Change introduction text
- [ ] Replace text on frontpage _Getting started_ and _Publishing Packages_
  - [x] Link to composer instructions
  - [x] Instructions for Drupal + Composer + Drupal Packagist
  - [x] link to drupal composer template for D7 and D8
  - [ ] Explain how packages are updated from drupal.org
  - [x] and where to post issues (on github)
- [x] Maybe replace the logo with [custom one](http://drupal-composer.org/icons/drupal-packagist.svg)
- [ ] Maybe adjust [colors](https://www.drupal.org/node/1051644) to drupal.org

Scribble

### CODE REVIEW

**Comment by webflo** [comment]
@derhasi Changed the logo and colors as first step. Please review.

**Comment by derhasi** [comment]
I added some more commits: added grunt/libsass for styles, changed colors and font to those from drupal-composer.org, updated the text for the frontpage, added favicon. Currenlty it looks something like that:

Screenshot from wip

Next step will be to update the about page and disable the user links.

**Comment by webflo** [comment]
Looks great. But i think Raleway font looks a little bit to thin. Maybe we should change `font-weight` to 400. https://www.google.com/fonts/specimen/Raleway

**Comment by derhasi** [comment]
I thinned out the about.html.twig. @webflo can you add some text to about on the update process. When doing that, can you also have a look at why the override about.html.twig seems not to be loaded (at least on my local installation).

I adjusted some styles for the package list and the page view.

I think we can roll out that PR after you made your changes, so we can be visually distinguished from the original packagist.

**Comment by webflo** [comment]
I think we go with the new/current design.

**Pull request closed without merging**
